### ISSUE TITLE
Doing regional Search breaks Website

### ISSUE THREAD

**Issue by cbleek** [cbleek/YawikDemoJobboard#2] opened 2017-11-16 14:39 UTC
When doing a regional Search on jobs.yawik.org, the is a JS error. You have to delete Cookies to make the Site work again.

![auswahl_999 622](https://user-images.githubusercontent.com/858642/32896758-2ff79a78-cae4-11e7-9333-b5982586dfd9.png)

**Comment by cbleek** [comment] 2017-11-16 14:43
Using the "clear=1" Parameter is enough to make the site working again

https://jobs.yawik.org/de/jobboard?clear=1

**Comment by cbleek** [comment] 2017-11-17 15:41
Problem was introduced when encoding Facets containing "&" Like "Sales & Marketing"

**Comment by TiSiE** [comment] 2017-11-17 16:33
The problem is in general the bad URI encoding of the core.searchform jquery plugin.

**Comment by TiSiE** [comment] 2017-11-17 16:44
This is fixed now with cross-solution/YAWIK@52cbfecb19be3c67502118d20ad59f680b44e004

**Closed as completed by TiSiE** 2017-11-17 16:44 UTC
